const menuItems = [
  {
    id: 1,
    name: "Classic Smash Burger",
    price: 16,
    image: "/images/menu/classic-smash.png",
    tagline: "Double smashed patties, caramelized onion, house sauce.",
    time: "10-12 MIN",
    bun: "Brioche",
    patty: "Beef",
    spice: "Mild",
  
  },
  {
    id: 2,
    name: "Spicy Jalapeño Burger",
    price: 18,
    image: "/images/menu/spicy-jalapeno.png",
    tagline: "Cheddar, pickled jalapeño, chipotle mayo, crisp lettuce.",
    time: "12-14 MIN",
    bun: "Brioche",
    patty: "Beef",
    spice: "Hot",
  },
  {
    id: 3,
    name: "Bacon Cheese Burger",
    price: 21,
    image: "/images/menu/bacon-cheese.png",
    tagline: "Crispy bacon, melted cheddar, smoky BBQ glaze.",
    time: "12-14 MIN",
    bun: "Potato",
    patty: "Beef",
    spice: "Mild",
  },
  {
    id: 4,
    name: "Veggie Delight Burger",
    price: 15,
    image: "/images/menu/veggie-delight.png",
    tagline: "Grilled portobello, roasted pepper, herb aioli.",
    time: "8-10 MIN",
    bun: "Whole Wheat",
    patty: "Veggie",
    spice: "Mild",
  },
  {
    id: 5,
    name: "Double Trouble Burger",
    price: 23,
    image: "/images/menu/double-trouble.png",
    tagline: "Two beef patties, double cheese, secret sauce stack.",
    time: "14-16 MIN",
    bun: "Brioche",
    patty: "Double Beef",
    spice: "Medium",
  },
  {
    id: 6,
    name: "BBQ Ranch Burger",
    price: 19,
    image: "/images/menu/bbq-ranch.png",
    tagline: "Smoky BBQ sauce, ranch drizzle, crispy onion straws.",
    time: "12-14 MIN",
    bun: "Sesame",
    patty: "Beef",
    spice: "Mild",
  },
 
  {
    id: 1,
    name: "Classic Smash Burger",
    price: 16,
    image: "/images/menu/classic-smash.png",
    tagline: "Double smashed patties, caramelized onion, house sauce.",
    time: "10-12 MIN",
    bun: "Brioche",
    patty: "Beef",
    spice: "Mild",
  },
  {
    id: 2,
    name: "Spicy Jalapeño Burger",
    price: 18,
    image: "/images/menu/spicy-jalapeno.png",
    tagline: "Cheddar, pickled jalapeño, chipotle mayo, crisp lettuce.",
    time: "12-14 MIN",
    bun: "Brioche",
    patty: "Beef",
    spice: "Hot",
  },
  {
    id: 3,
    name: "Bacon Cheese Burger",
    price: 21,
    image: "/images/menu/bacon-cheese.png",
    tagline: "Crispy bacon, melted cheddar, smoky BBQ glaze.",
    time: "12-14 MIN",
    bun: "Potato",
    patty: "Beef",
    spice: "Mild",
  },
  {
    id: 4,
    name: "Veggie Delight Burger",
    price: 15,
    image: "/images/menu/veggie-delight.png",
    tagline: "Grilled portobello, roasted pepper, herb aioli.",
    time: "8-10 MIN",
    bun: "Whole Wheat",
    patty: "Veggie",
    spice: "Mild",
  },
  {
    id: 5,
    name: "Double Trouble Burger",
    price: 23,
    image: "/images/menu/double-trouble.png",
    tagline: "Two beef patties, double cheese, secret sauce stack.",
    time: "14-16 MIN",
    bun: "Brioche",
    patty: "Double Beef",
    spice: "Medium",
  },
  {
    id: 6,
    name: "BBQ Ranch Burger",
    price: 19,
    image: "/images/menu/bbq-ranch.png",
    tagline: "Smoky BBQ sauce, ranch drizzle, crispy onion straws.",
    time: "12-14 MIN",
    bun: "Sesame",
    patty: "Beef",
    spice: "Mild",
  },
 
];

export default menuItems;
