export const menuItems = [
  {
    id: 1,
    name: "Classic Smash Burger",
    price: 16,
    image: "/images/demo.png",
    type: "Burger",
    prepTime: "12-14 min",
    quickDetails: [
      { label: "Bun", value: "Brioche" },
      { label: "Patty", value: "Beef" },
      { label: "Spice", value: "Mild" },
    ],
    calories: 810,
    protein: 34,
  },
  {
    id: 2,
    name: "BBQ Bacon Stack",
    price: 18,
    image: "/images/demo.png",
    type: "Burger",
    prepTime: "14-16 min",
    quickDetails: [
      { label: "Bun", value: "Brioche" },
      { label: "Patty", value: "Beef" },
      { label: "Spice", value: "Mild" },
    ],
    calories: 920,
    protein: 38,
  },
  {
    id: 3,
    name: "Truffle Mushroom Swiss",
    price: 19,
    image: "/images/demo.png",
    type: "Burger",
    prepTime: "14-16 min",
    quickDetails: [
      { label: "Bun", value: "Potato" },
      { label: "Patty", value: "Beef" },
      { label: "Spice", value: "Mild" },
    ],
    calories: 880,
    protein: 36,
  },
  {
    id: 4,
    name: "Spicy Jalapeno Melt",
    price: 17,
    image: "/images/demo.png",
    type: "Burger",
    prepTime: "12-14 min",
    quickDetails: [
      { label: "Bun", value: "Brioche" },
      { label: "Patty", value: "Beef" },
      { label: "Spice", value: "Hot" },
    ],
    calories: 850,
    protein: 35,
  },
  {
    id: 5,
    name: "Double Cheese Deluxe",
    price: 18,
    image: "/images/demo.png",
    type: "Burger",
    prepTime: "14-16 min",
    quickDetails: [
      { label: "Bun", value: "Brioche" },
      { label: "Patty", value: "Beef x2" },
      { label: "Spice", value: "Mild" },
    ],
    calories: 1040,
    protein: 46,
  },
  {
    id: 6,
    name: "Crispy Chicken Burger",
    price: 15,
    image: "/images/demo.png",
    type: "Chicken",
    prepTime: "10-12 min",
    quickDetails: [
      { label: "Bun", value: "Sesame" },
      { label: "Chicken", value: "Fried" },
      { label: "Spice", value: "Mild" },
    ],
    calories: 760,
    protein: 32,
  },
  {
    id: 7,
    name: "Grilled Chicken Avocado",
    price: 16,
    image: "/images/demo.png",
    type: "Chicken",
    prepTime: "12-14 min",
    quickDetails: [
      { label: "Bun", value: "Wheat" },
      { label: "Chicken", value: "Grilled" },
      { label: "Spice", value: "Mild" },
    ],
    calories: 680,
    protein: 40,
  },
  {
    id: 8,
    name: "Nashville Hot Chicken",
    price: 17,
    image: "/images/demo.png",
    type: "Chicken",
    prepTime: "12-14 min",
    quickDetails: [
      { label: "Bun", value: "Sesame" },
      { label: "Chicken", value: "Fried" },
      { label: "Spice", value: "Hot" },
    ],
    calories: 810,
    protein: 34,
  },
  {
    id: 9,
    name: "Veggie Black Bean Burger",
    price: 14,
    image: "/images/demo.png",
    type: "veg",
    prepTime: "10-12 min",
    quickDetails: [
      { label: "Bun", value: "Brioche" },
      { label: "Patty", value: "Black Bean" },
      { label: "Spice", value: "Mild" },
    ],
    calories: 620,
    protein: 20,
  },
  {
    id: 10,
    name: "Grilled Halloumi Burger",
    price: 15,
    image: "/images/demo.png",
    type: "veg",
    prepTime: "10-12 min",
    quickDetails: [
      { label: "Bun", value: "Brioche" },
      { label: "Patty", value: "Halloumi" },
      { label: "Spice", value: "Mild" },
    ],
    calories: 700,
    protein: 24,
  },
  {
    id: 11,
    name: "Chicken Teriyaki Rice Bowl",
    price: 14,
    image: "/images/demo.png",
    type: "Rice",
    prepTime: "10-12 min",
    quickDetails: [
      { label: "Rice", value: "Steamed" },
      { label: "Protein", value: "Chicken" },
      { label: "Spice", value: "Mild" },
    ],
    calories: 640,
    protein: 30,
  },
  {
    id: 12,
    name: "Spicy Korean Beef Rice Bowl",
    price: 16,
    image: "/images/demo.png",
    type: "Rice",
    prepTime: "12-14 min",
    quickDetails: [
      { label: "Rice", value: "Steamed" },
      { label: "Protein", value: "Beef" },
      { label: "Spice", value: "Hot" },
    ],
    calories: 720,
    protein: 33,
  },
  {
    id: 13,
    name: "Loaded Cheese Fries",
    price: 9,
    image: "/images/demo.png",
    type: "Sides",
    prepTime: "6-8 min",
    quickDetails: [
      { label: "Style", value: "Loaded" },
      { label: "Dip", value: "Cheese" },
      { label: "Spice", value: "Mild" },
    ],
    calories: 540,
    protein: 12,
  },
  {
    id: 14,
    name: "Crispy Onion Rings",
    price: 8,
    image: "/images/demo.png",
    type: "Sides",
    prepTime: "6-8 min",
    quickDetails: [
      { label: "Style", value: "Battered" },
      { label: "Dip", value: "Chipotle" },
      { label: "Spice", value: "Mild" },
    ],
    calories: 460,
    protein: 6,
  },
  {
    id: 15,
    name: "Classic Fries",
    price: 6,
    image: "/images/demo.png",
    type: "Sides",
    prepTime: "5-7 min",
    quickDetails: [
      { label: "Style", value: "Crispy" },
      { label: "Dip", value: "Ketchup" },
      { label: "Spice", value: "None" },
    ],
    calories: 380,
    protein: 5,
  },
  {
    id: 16,
    name: "Classic Vanilla Milkshake",
    price: 7,
    image: "/images/demo.png",
    type: "Beverages",
    prepTime: "3-5 min",
    quickDetails: [
      { label: "Size", value: "16oz" },
      { label: "Type", value: "Shake" },
      { label: "Ice", value: "Yes" },
    ],
    calories: 480,
    protein: 9,
  },
  {
    id: 17,
    name: "Chocolate Fudge Shake",
    price: 8,
    image: "/images/demo.png",
    type: "Beverages",
    prepTime: "3-5 min",
    quickDetails: [
      { label: "Size", value: "16oz" },
      { label: "Type", value: "Shake" },
      { label: "Ice", value: "Yes" },
    ],
    calories: 540,
    protein: 10,
  },
  {
    id: 18,
    name: "Fresh Lemonade",
    price: 5,
    image: "/images/demo.png",
    type: "Beverages",
    prepTime: "2-3 min",
    quickDetails: [
      { label: "Size", value: "16oz" },
      { label: "Type", value: "Cold" },
      { label: "Ice", value: "Yes" },
    ],
    calories: 140,
    protein: 0,
  },
  {
    id: 19,
    name: "Iced Coke Float",
    price: 6,
    image: "/images/demo.png",
    type: "Beverages",
    prepTime: "2-3 min",
    quickDetails: [
      { label: "Size", value: "16oz" },
      { label: "Type", value: "Float" },
      { label: "Ice", value: "Yes" },
    ],
    calories: 260,
    protein: 2,
  },
  {
    id: 20,
    name: "Chocolate Brownie Sundae",
    price: 9,
    image: "/images/demo.png",
    type: "Dessert",
    prepTime: "5-7 min",
    quickDetails: [
      { label: "Base", value: "Brownie" },
      { label: "Topping", value: "Fudge" },
      { label: "Serve", value: "Warm" },
    ],
    calories: 690,
    protein: 8,
  },
];

export   const categories = [
  "All",
  "Starters",
  "Burger",
  "Chicken",
  "Rise",
  "Sides",
  "Dessert",
  "Beverages",
  "Chef Specials",
];
